/*
 * WSO2 API Manager - Admin
 * This document specifies a **RESTful API** for WSO2 **API Manager** - Admin Portal. Please see [full swagger definition](https://raw.githubusercontent.com/wso2/carbon-apimgt/v6.1.66/components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/resources/admin-api.yaml) of the API which is written using [swagger 2.0](http://swagger.io/) specification. 
 *
 * OpenAPI spec version: 0.11.0
 * Contact: architecture@wso2.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.wso2.carbon.apimgt.samples.utils.admin.rest.client.api;

import org.wso2.carbon.apimgt.samples.utils.admin.rest.client.ApiException;
import org.wso2.carbon.apimgt.samples.utils.admin.rest.client.model.AdvancedThrottlePolicy;
import org.wso2.carbon.apimgt.samples.utils.admin.rest.client.model.Error;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AdvancedPolicyIndividualApi
 */
@Ignore
public class AdvancedPolicyIndividualApiTest {

    private final AdvancedPolicyIndividualApi api = new AdvancedPolicyIndividualApi();

    
    /**
     * Delete an Advanced Throttling Policy
     *
     * Deletes an Advanced level throttling policy. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void throttlingPoliciesAdvancedPolicyIdDeleteTest() throws ApiException {
        String policyId = null;
        String ifMatch = null;
        String ifUnmodifiedSince = null;
        api.throttlingPoliciesAdvancedPolicyIdDelete(policyId, ifMatch, ifUnmodifiedSince);

        // TODO: test validations
    }
    
    /**
     * Get an Advanced Policy
     *
     * Retrieves an Advanced Policy. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void throttlingPoliciesAdvancedPolicyIdGetTest() throws ApiException {
        String policyId = null;
        String ifNoneMatch = null;
        String ifModifiedSince = null;
        AdvancedThrottlePolicy response = api.throttlingPoliciesAdvancedPolicyIdGet(policyId, ifNoneMatch, ifModifiedSince);

        // TODO: test validations
    }
    
    /**
     * Update an Advanced Throttling Policy
     *
     * Updates an existing Advanced level throttling policy. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void throttlingPoliciesAdvancedPolicyIdPutTest() throws ApiException {
        String policyId = null;
        AdvancedThrottlePolicy body = null;
        String contentType = null;
        String ifMatch = null;
        String ifUnmodifiedSince = null;
        AdvancedThrottlePolicy response = api.throttlingPoliciesAdvancedPolicyIdPut(policyId, body, contentType, ifMatch, ifUnmodifiedSince);

        // TODO: test validations
    }
    
}
