/*
 * WSO2 API Manager - Admin
 * This document specifies a **RESTful API** for WSO2 **API Manager** - Admin Portal. Please see [full swagger definition](https://raw.githubusercontent.com/wso2/carbon-apimgt/v6.1.66/components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/resources/admin-api.yaml) of the API which is written using [swagger 2.0](http://swagger.io/) specification. 
 *
 * OpenAPI spec version: 0.11.0
 * Contact: architecture@wso2.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.wso2.carbon.apimgt.samples.utils.admin.rest.client.api;

import org.wso2.carbon.apimgt.samples.utils.admin.rest.client.ApiException;
import org.wso2.carbon.apimgt.samples.utils.admin.rest.client.model.ApplicationThrottlePolicy;
import org.wso2.carbon.apimgt.samples.utils.admin.rest.client.model.ApplicationThrottlePolicyList;
import org.wso2.carbon.apimgt.samples.utils.admin.rest.client.model.Error;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ApplicationPolicyCollectionApi
 */
@Ignore
public class ApplicationPolicyCollectionApiTest {

    private final ApplicationPolicyCollectionApi api = new ApplicationPolicyCollectionApi();

    
    /**
     * Get all Application Throttling Policies
     *
     * Retrieves all existing application throttling policies. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void throttlingPoliciesApplicationGetTest() throws ApiException {
        String accept = null;
        String ifNoneMatch = null;
        String ifModifiedSince = null;
        ApplicationThrottlePolicyList response = api.throttlingPoliciesApplicationGet(accept, ifNoneMatch, ifModifiedSince);

        // TODO: test validations
    }
    
    /**
     * Add an Application Throttling Policy
     *
     * This operation can be used to add a new application level throttling policy. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void throttlingPoliciesApplicationPostTest() throws ApiException {
        ApplicationThrottlePolicy body = null;
        String contentType = null;
        ApplicationThrottlePolicy response = api.throttlingPoliciesApplicationPost(body, contentType);

        // TODO: test validations
    }
    
}
