/*
 * WSO2 API Manager - Admin
 * This document specifies a **RESTful API** for WSO2 **API Manager** - Admin Portal. Please see [full swagger definition](https://raw.githubusercontent.com/wso2/carbon-apimgt/v6.1.66/components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/resources/admin-api.yaml) of the API which is written using [swagger 2.0](http://swagger.io/) specification. 
 *
 * OpenAPI spec version: 0.11.0
 * Contact: architecture@wso2.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.wso2.carbon.apimgt.samples.utils.admin.rest.client.api;

import org.wso2.carbon.apimgt.samples.utils.admin.rest.client.ApiException;
import org.wso2.carbon.apimgt.samples.utils.admin.rest.client.model.BlockingCondition;
import org.wso2.carbon.apimgt.samples.utils.admin.rest.client.model.BlockingConditionList;
import org.wso2.carbon.apimgt.samples.utils.admin.rest.client.model.Error;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BlacklistCollectionApi
 */
@Ignore
public class BlacklistCollectionApiTest {

    private final BlacklistCollectionApi api = new BlacklistCollectionApi();

    
    /**
     * Get all blocking condtions
     *
     * Retrieves all existing blocking condtions. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void throttlingBlacklistGetTest() throws ApiException {
        String accept = null;
        String ifNoneMatch = null;
        String ifModifiedSince = null;
        BlockingConditionList response = api.throttlingBlacklistGet(accept, ifNoneMatch, ifModifiedSince);

        // TODO: test validations
    }
    
    /**
     * Add a Blocking condition
     *
     * Adds a new Blocking condition. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void throttlingBlacklistPostTest() throws ApiException {
        BlockingCondition body = null;
        String contentType = null;
        BlockingCondition response = api.throttlingBlacklistPost(body, contentType);

        // TODO: test validations
    }
    
}
