/*
 * WSO2 API Manager - Admin
 * This document specifies a **RESTful API** for WSO2 **API Manager** - Admin Portal. Please see [full swagger definition](https://raw.githubusercontent.com/wso2/carbon-apimgt/v6.1.66/components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/resources/admin-api.yaml) of the API which is written using [swagger 2.0](http://swagger.io/) specification. 
 *
 * OpenAPI spec version: 0.11.0
 * Contact: architecture@wso2.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.wso2.carbon.apimgt.samples.utils.admin.rest.client.api;

import org.wso2.carbon.apimgt.samples.utils.admin.rest.client.ApiException;
import org.wso2.carbon.apimgt.samples.utils.admin.rest.client.model.CustomRule;
import org.wso2.carbon.apimgt.samples.utils.admin.rest.client.model.CustomRuleList;
import org.wso2.carbon.apimgt.samples.utils.admin.rest.client.model.Error;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CustomRulesCollectionApi
 */
@Ignore
public class CustomRulesCollectionApiTest {

    private final CustomRulesCollectionApi api = new CustomRulesCollectionApi();

    
    /**
     * Get all Custom Rules
     *
     * Retrieves all Custom Rules.  **NOTE:** * Only super tenant users are allowed for this operation. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void throttlingPoliciesCustomGetTest() throws ApiException {
        String accept = null;
        String ifNoneMatch = null;
        String ifModifiedSince = null;
        CustomRuleList response = api.throttlingPoliciesCustomGet(accept, ifNoneMatch, ifModifiedSince);

        // TODO: test validations
    }
    
    /**
     * Add a Custom Rule
     *
     * Adds a new Custom Rule.  **NOTE:** * Only super tenant users are allowed for this operation. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void throttlingPoliciesCustomPostTest() throws ApiException {
        CustomRule body = null;
        String contentType = null;
        CustomRule response = api.throttlingPoliciesCustomPost(body, contentType);

        // TODO: test validations
    }
    
}
