/*
 * WSO2 API Manager - Admin
 * This document specifies a **RESTful API** for WSO2 **API Manager** - Admin Portal. Please see [full swagger definition](https://raw.githubusercontent.com/wso2/carbon-apimgt/v6.1.66/components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/resources/admin-api.yaml) of the API which is written using [swagger 2.0](http://swagger.io/) specification. 
 *
 * OpenAPI spec version: 0.11.0
 * Contact: architecture@wso2.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.wso2.carbon.apimgt.samples.utils.admin.rest.client.api;

import org.wso2.carbon.apimgt.samples.utils.admin.rest.client.ApiException;
import org.wso2.carbon.apimgt.samples.utils.admin.rest.client.model.CustomRule;
import org.wso2.carbon.apimgt.samples.utils.admin.rest.client.model.Error;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CustomRulesIndividualApi
 */
@Ignore
public class CustomRulesIndividualApiTest {

    private final CustomRulesIndividualApi api = new CustomRulesIndividualApi();

    
    /**
     * Delete a Custom Rule
     *
     * Delete a Custom Rule. We need to provide the Id of the policy as a path parameter.  **NOTE:** * Only super tenant users are allowed for this operation. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void throttlingPoliciesCustomRuleIdDeleteTest() throws ApiException {
        String ruleId = null;
        String ifMatch = null;
        String ifUnmodifiedSince = null;
        api.throttlingPoliciesCustomRuleIdDelete(ruleId, ifMatch, ifUnmodifiedSince);

        // TODO: test validations
    }
    
    /**
     * Get a Custom Rule
     *
     * Retrieves a Custom Rule. We need to provide the policy Id as a path parameter.  **NOTE:** * Only super tenant users are allowed for this operation. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void throttlingPoliciesCustomRuleIdGetTest() throws ApiException {
        String ruleId = null;
        String ifNoneMatch = null;
        String ifModifiedSince = null;
        CustomRule response = api.throttlingPoliciesCustomRuleIdGet(ruleId, ifNoneMatch, ifModifiedSince);

        // TODO: test validations
    }
    
    /**
     * Update a Custom Rule
     *
     * Updates an existing Custom Rule.  **NOTE:** * Only super tenant users are allowed for this operation. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void throttlingPoliciesCustomRuleIdPutTest() throws ApiException {
        String ruleId = null;
        CustomRule body = null;
        String contentType = null;
        String ifMatch = null;
        String ifUnmodifiedSince = null;
        CustomRule response = api.throttlingPoliciesCustomRuleIdPut(ruleId, body, contentType, ifMatch, ifUnmodifiedSince);

        // TODO: test validations
    }
    
}
