/*
 * WSO2 API Manager - Admin
 * This document specifies a **RESTful API** for WSO2 **API Manager** - Admin Portal. Please see [full swagger definition](https://raw.githubusercontent.com/wso2/carbon-apimgt/v6.1.66/components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/resources/admin-api.yaml) of the API which is written using [swagger 2.0](http://swagger.io/) specification. 
 *
 * OpenAPI spec version: 0.11.0
 * Contact: architecture@wso2.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.wso2.carbon.apimgt.samples.utils.admin.rest.client.api;

import org.wso2.carbon.apimgt.samples.utils.admin.rest.client.ApiException;
import org.wso2.carbon.apimgt.samples.utils.admin.rest.client.model.Error;
import org.wso2.carbon.apimgt.samples.utils.admin.rest.client.model.SubscriptionThrottlePolicy;
import org.wso2.carbon.apimgt.samples.utils.admin.rest.client.model.SubscriptionThrottlePolicyList;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SubscriptionPolicyCollectionApi
 */
@Ignore
public class SubscriptionPolicyCollectionApiTest {

    private final SubscriptionPolicyCollectionApi api = new SubscriptionPolicyCollectionApi();

    
    /**
     * Get all Subscription Throttling Policies
     *
     * This operation can be used to retrieve all Subscription level throttling policies. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void throttlingPoliciesSubscriptionGetTest() throws ApiException {
        String accept = null;
        String ifNoneMatch = null;
        String ifModifiedSince = null;
        SubscriptionThrottlePolicyList response = api.throttlingPoliciesSubscriptionGet(accept, ifNoneMatch, ifModifiedSince);

        // TODO: test validations
    }
    
    /**
     * Add a Subscription Throttling Policy
     *
     * This operation can be used to add a Subscription level throttling policy specifying the details of the policy in the payload. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void throttlingPoliciesSubscriptionPostTest() throws ApiException {
        SubscriptionThrottlePolicy body = null;
        String contentType = null;
        SubscriptionThrottlePolicy response = api.throttlingPoliciesSubscriptionPost(body, contentType);

        // TODO: test validations
    }
    
}
