/*
 * WSO2 API Manager - Admin
 * This document specifies a **RESTful API** for WSO2 **API Manager** - Admin Portal. Please see [full swagger definition](https://raw.githubusercontent.com/wso2/carbon-apimgt/v6.1.66/components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/resources/admin-api.yaml) of the API which is written using [swagger 2.0](http://swagger.io/) specification. 
 *
 * OpenAPI spec version: 0.11.0
 * Contact: architecture@wso2.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.wso2.carbon.apimgt.samples.utils.admin.rest.client.api;

import org.wso2.carbon.apimgt.samples.utils.admin.rest.client.ApiException;
import org.wso2.carbon.apimgt.samples.utils.admin.rest.client.model.Error;
import org.wso2.carbon.apimgt.samples.utils.admin.rest.client.model.SubscriptionThrottlePolicy;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SubscriptionPolicyIndividualApi
 */
@Ignore
public class SubscriptionPolicyIndividualApiTest {

    private final SubscriptionPolicyIndividualApi api = new SubscriptionPolicyIndividualApi();

    
    /**
     * Delete a Subscription Policy
     *
     * This operation can be used to delete a subscription-level throttling policy specifying the Id of the policy as a path paramter. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void throttlingPoliciesSubscriptionPolicyIdDeleteTest() throws ApiException {
        String policyId = null;
        String ifMatch = null;
        String ifUnmodifiedSince = null;
        api.throttlingPoliciesSubscriptionPolicyIdDelete(policyId, ifMatch, ifUnmodifiedSince);

        // TODO: test validations
    }
    
    /**
     * Get a Subscription Policy
     *
     * Retrieve a single subscription-level throttling policy. We should provide the Id of the policy as a path parameter. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void throttlingPoliciesSubscriptionPolicyIdGetTest() throws ApiException {
        String policyId = null;
        String ifNoneMatch = null;
        String ifModifiedSince = null;
        SubscriptionThrottlePolicy response = api.throttlingPoliciesSubscriptionPolicyIdGet(policyId, ifNoneMatch, ifModifiedSince);

        // TODO: test validations
    }
    
    /**
     * Update a Subscription Policy
     *
     * Updates an existing subscription-level throttling policy. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void throttlingPoliciesSubscriptionPolicyIdPutTest() throws ApiException {
        String policyId = null;
        SubscriptionThrottlePolicy body = null;
        String contentType = null;
        String ifMatch = null;
        String ifUnmodifiedSince = null;
        SubscriptionThrottlePolicy response = api.throttlingPoliciesSubscriptionPolicyIdPut(policyId, body, contentType, ifMatch, ifUnmodifiedSince);

        // TODO: test validations
    }
    
}
