/*
 * WSO2 API Manager - Publisher API
 * This specifies a **RESTful API** for WSO2 **API Manager** - Publisher.  Please see [full swagger definition](https://raw.githubusercontent.com/wso2/carbon-apimgt/v6.1.66/components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/resources/publisher-api.yaml) of the API which is written using [swagger 2.0](http://swagger.io/) specification. 
 *
 * OpenAPI spec version: 0.11.0
 * Contact: architecture@wso2.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.wso2.carbon.apimgt.samples.utils.publisher.rest.client.api;

import org.wso2.carbon.apimgt.samples.utils.publisher.rest.client.ApiException;
import org.wso2.carbon.apimgt.samples.utils.publisher.rest.client.model.Error;
import org.wso2.carbon.apimgt.samples.utils.publisher.rest.client.model.Mediation;
import org.wso2.carbon.apimgt.samples.utils.publisher.rest.client.model.MediationList;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MediationPolicyCollectionApi
 */
@Ignore
public class MediationPolicyCollectionApiTest {

    private final MediationPolicyCollectionApi api = new MediationPolicyCollectionApi();

    
    /**
     * Get all mediation policies of an API 
     *
     * This operation provides you a list of available mediation policies of an API. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apisApiIdPoliciesMediationGetTest() throws ApiException {
        String apiId = null;
        Integer limit = null;
        Integer offset = null;
        String query = null;
        String accept = null;
        String ifNoneMatch = null;
        MediationList response = api.apisApiIdPoliciesMediationGet(apiId, limit, offset, query, accept, ifNoneMatch);

        // TODO: test validations
    }
    
    /**
     * Add an API specific mediation policy
     *
     * This operation can be used to add an API specifc mediation policy. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apisApiIdPoliciesMediationPostTest() throws ApiException {
        Mediation body = null;
        String apiId = null;
        String contentType = null;
        String ifMatch = null;
        String ifUnmodifiedSince = null;
        Mediation response = api.apisApiIdPoliciesMediationPost(body, apiId, contentType, ifMatch, ifUnmodifiedSince);

        // TODO: test validations
    }
    
    /**
     * Get all global level mediation policies 
     *
     * This operation provides you a list of available all global level mediation policies. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void policiesMediationGetTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        String query = null;
        String accept = null;
        String ifNoneMatch = null;
        MediationList response = api.policiesMediationGet(limit, offset, query, accept, ifNoneMatch);

        // TODO: test validations
    }
    
}
