/*
 * WSO2 API Manager - Publisher API
 * This specifies a **RESTful API** for WSO2 **API Manager** - Publisher.  Please see [full swagger definition](https://raw.githubusercontent.com/wso2/carbon-apimgt/v6.1.66/components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/resources/publisher-api.yaml) of the API which is written using [swagger 2.0](http://swagger.io/) specification. 
 *
 * OpenAPI spec version: 0.11.0
 * Contact: architecture@wso2.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.wso2.carbon.apimgt.samples.utils.publisher.rest.client.api;

import org.wso2.carbon.apimgt.samples.utils.publisher.rest.client.ApiException;
import org.wso2.carbon.apimgt.samples.utils.publisher.rest.client.model.Error;
import org.wso2.carbon.apimgt.samples.utils.publisher.rest.client.model.ExtendedSubscription;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SubscriptionIndividualApi
 */
@Ignore
public class SubscriptionIndividualApiTest {

    private final SubscriptionIndividualApi api = new SubscriptionIndividualApi();

    
    /**
     * Block a subscription
     *
     * This operation can be used to block a subscription. Along with the request, &#x60;blockState&#x60; must be specified as a query parameter.  1. &#x60;BLOCKED&#x60; : Subscription is completely blocked for both Production and Sandbox environments. 2. &#x60;PROD_ONLY_BLOCKED&#x60; : Subscription is blocked for Production environment only. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void subscriptionsBlockSubscriptionPostTest() throws ApiException {
        String subscriptionId = null;
        String blockState = null;
        String ifMatch = null;
        String ifUnmodifiedSince = null;
        api.subscriptionsBlockSubscriptionPost(subscriptionId, blockState, ifMatch, ifUnmodifiedSince);

        // TODO: test validations
    }
    
    /**
     * Get details of a subscription
     *
     * This operation can be used to get details of a single subscription. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void subscriptionsSubscriptionIdGetTest() throws ApiException {
        String subscriptionId = null;
        String accept = null;
        String ifNoneMatch = null;
        String ifModifiedSince = null;
        ExtendedSubscription response = api.subscriptionsSubscriptionIdGet(subscriptionId, accept, ifNoneMatch, ifModifiedSince);

        // TODO: test validations
    }
    
    /**
     * Unblock a Subscription
     *
     * This operation can be used to unblock a subscription specifying the subscription Id. The subscription will be fully unblocked after performing this operation. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void subscriptionsUnblockSubscriptionPostTest() throws ApiException {
        String subscriptionId = null;
        String ifMatch = null;
        String ifUnmodifiedSince = null;
        api.subscriptionsUnblockSubscriptionPost(subscriptionId, ifMatch, ifUnmodifiedSince);

        // TODO: test validations
    }
    
}
