/*
 * WSO2 API Manager - Store
 * This specifies a **RESTful API** for WSO2 **API Manager** - Store.  Please see [full swagger definition](https://raw.githubusercontent.com/wso2/carbon-apimgt/v6.1.66/components/apimgt/org.wso2.carbon.apimgt.rest.api.store/src/main/resources/store-api.yaml) of the API which is written using [swagger 2.0](http://swagger.io/) specification. 
 *
 * OpenAPI spec version: 0.11.0
 * Contact: architecture@wso2.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.wso2.carbon.apimgt.samples.utils.store.rest.client.api;

import org.wso2.carbon.apimgt.samples.utils.store.rest.client.ApiException;
import org.wso2.carbon.apimgt.samples.utils.store.rest.client.model.ApplicationList;
import org.wso2.carbon.apimgt.samples.utils.store.rest.client.model.Error;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ApplicationCollectionApi
 */
@Ignore
public class ApplicationCollectionApiTest {

    private final ApplicationCollectionApi api = new ApplicationCollectionApi();

    
    /**
     * Retrieve/Search applications 
     *
     * This operation can be used to retrieve list of applications that is belonged to the user associated with the provided access token. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void applicationsGetTest() throws ApiException {
        String groupId = null;
        String query = null;
        Integer limit = null;
        Integer offset = null;
        String accept = null;
        String ifNoneMatch = null;
        ApplicationList response = api.applicationsGet(groupId, query, limit, offset, accept, ifNoneMatch);

        // TODO: test validations
    }
    
}
